name: Dornacraft-PlayerManager
version: 1.0
author: Voltariuss
main: fr.voltariuss.dornacraftplayermanager.DornacraftPlayerManager
depend: [Dornacraft-API, Dornacraft-Cache]
commands:
  rankmanager:
    description: Gestion des rangs des joueurs
  subrankmanager:
    description: Gestion des sous-rangs des joueurs
  permissionmanager:
    description: Gestion des permissions des joueurs
  levelmanager:
    description: Gestion des niveaux des joueurs
  prefixmanager:
    description: Gestion des prefixes des joueurs